common: &common
  version: cdt
  network: ansible_default
  mountpath: /root/ansible/nfs
  dnsserver: 10.10.28.116

client:
  cryptopath: benchmarks/config_raft
  usecmd: false
  orgs: # 数组
    - org1
    - org2
fabric-network:
  peer:
    peer0.org1.example.com:  
      <<: *common
      host: 10.10.7.46
      port: 7051
    peer1.org1.example.com:  
      <<: *common
      host: 10.10.7.46
      port: 7061
    peer0.org2.example.com:  
      <<: *common
      host: 10.10.7.47
      port: 7078
    peer1.org2.example.com:  
      <<: *common
      host: 10.10.7.47
      port: 7081
  
  
  # 修改orderer端口要主要configtx.yaml中的端口配置
  orderer:
    orderer0.example.com:  
      <<: *common
      host: 10.10.7.52
      port: 7050
    orderer1.example.com:  
      <<: *common
      host: 10.10.7.52
      port: 8050
    orderer2.example.com:  
      <<: *common
      host: 10.10.7.52
      port: 9050
  ca:
    ca.org1.example.com:  
      <<: *common
      host: 10.10.7.52
      port: 7054
    ca.org2.example.com:  
      <<: *common
      host: 10.10.7.52
      port: 8054
    