---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  workers:
    type: local
    number: 8
  rounds:
  - label: smallOperations
    txNumber: 5000
    rateControl:
      type: fixed-rate
      opts:
        tps: 500
    arguments:
      accounts: 5000
      txnPerBatch: 1
    callback: benchmarks/scenario/smallbank/smallbankOperations.js
  - label: query
    txNumber: 5000
    rateControl:
      type: fixed-rate
      opts:
        tps: 500
    callback: benchmarks/scenario/smallbank/query.js


monitor:
  type: docker
  docker:
    containers:
    {% for host in fabric %}
      - {{host}}
    {% endfor %}
    charting:
      bar:
        metrics: [all]
      polar:
        metrics: [all]
  interval: 1

